### ISSUE TITLE
Read DHT11 sensor values

### ISSUE THREAD

**Issue by Junumboxo** [Junumboxo/IoT-Bootcamp-project-Arduino#1]
Read the values of _humidity and temperature_ from the sensor DHT11

![image](https://user-images.githubusercontent.com/44647094/83999545-a1d66a80-a96b-11ea-8e9b-065ab33fe65e.png)
![image](https://user-images.githubusercontent.com/44647094/83999646-d21e0900-a96b-11ea-94fa-ec16283c7e14.png)

**Comment by alexandra0292** [comment]
#include <DHT.h>
#define DHTPIN 8
#define DHTTYPE DHT11   // DHT 11
 
DHT dht(DHTPIN, DHTTYPE);
  
void InitTemperatureDHT() {
    dht.begin();
}
 
float GetTemperatureDHT() {
  //  Read temperature as Celsius (the default)
    float t = dht.readTemperature();
//      for humidity:
    float h = dht.readHumidity();
    if (isnan(t)) {
      Serial.println(F("Failed to read from DHT sensor!"));
      return -1;
    }
    // else
  return t;
}

 
void setup() {
    Serial.begin(9600);
    InitTemperatureDHT();
    
}
 
void loop() {
    float value = GetTemperatureDHT();
  
    Serial.println(value);
    delay(1000);
}
