### ISSUE TITLE
Read GAS SENSOR values

### ISSUE THREAD

**Issue by Junumboxo** [Junumboxo/IoT-Bootcamp-project-Arduino#11]

**Comment by alexandra0292** [comment]
MQ2_results
17.00
17.00
17.00
17.00
17.00
17.00
18.00
18.00
18.00
18.00
18.00
18.00
19.00
19.00
19.00
19.00
19.00
19.00
19.00
19.00
18.00
17.00
16.00
16.00
15.00
16.00
16.00
16.00
16.00
16.00
17.00
17.00

**Comment by Junumboxo** [comment]
Option 1 - https://www.hackster.io/m_karim02/arduino-and-mq2-gas-sensor-57f98c
Option 2 - https://lastminuteengineers.com/mq2-gas-senser-arduino-tutorial/ (an easier one)
